# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calendar_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 800)
        Form.setStyleSheet("background-color: rgb(53, 53, 53);\n"
"color: rgb(253, 253, 253);\n"
"font-weight: bold;\n"
"text-align: center;")
        self.currMonth = QtWidgets.QLabel(Form)
        self.currMonth.setGeometry(QtCore.QRect(30, 80, 90, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.currMonth.setFont(font)
        self.currMonth.setObjectName("currMonth")
        self.currYear = QtWidgets.QLabel(Form)
        self.currYear.setGeometry(QtCore.QRect(115, 80, 75, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.currYear.setFont(font)
        self.currYear.setStyleSheet("font-weight: none;")
        self.currYear.setObjectName("currYear")
        self.addEventButton = QtWidgets.QPushButton(Form)
        self.addEventButton.setGeometry(QtCore.QRect(30, 20, 40, 40))
        self.addEventButton.setText("")
        self.addEventButton.setObjectName("addEventButton")
        self.dayButton = QtWidgets.QPushButton(Form)
        self.dayButton.setGeometry(QtCore.QRect(335, 20, 75, 40))
        self.dayButton.setObjectName("dayButton")
        self.weekButton = QtWidgets.QPushButton(Form)
        self.weekButton.setGeometry(QtCore.QRect(415, 20, 75, 40))
        self.weekButton.setObjectName("weekButton")
        self.monthButton = QtWidgets.QPushButton(Form)
        self.monthButton.setGeometry(QtCore.QRect(500, 20, 75, 40))
        self.monthButton.setObjectName("monthButton")
        self.yearButton = QtWidgets.QPushButton(Form)
        self.yearButton.setGeometry(QtCore.QRect(585, 20, 75, 40))
        self.yearButton.setObjectName("yearButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(100, 140, 871, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout.addWidget(self.label_15)
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout.addWidget(self.label_19)
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout.addWidget(self.label_18)
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_17.setStyleSheet("text-align: center;")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout.addWidget(self.label_17)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout.addWidget(self.label_16)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(30, 180, 940, 600))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 938, 598))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.currMonth.setText(_translate("Form", "MARCH"))
        self.currYear.setText(_translate("Form", "2025"))
        self.dayButton.setText(_translate("Form", "Day"))
        self.weekButton.setText(_translate("Form", "Week"))
        self.monthButton.setText(_translate("Form", "Month"))
        self.yearButton.setText(_translate("Form", "Year"))
        self.label_15.setText(_translate("Form", "Sun 2"))
        self.label_19.setText(_translate("Form", "Mon 3"))
        self.label_18.setText(_translate("Form", "Tue 4"))
        self.label_17.setText(_translate("Form", "Wed 5"))
        self.label_16.setText(_translate("Form", "Thu 6"))
        self.label_14.setText(_translate("Form", "Fri 7"))
        self.label_13.setText(_translate("Form", "Sat 8"))
